# syntax=docker/dockerfile:1

FROM node:17.4-alpine3.15
ENV NODE_ENV=production

WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]

RUN npm install
# TODO: Edit the COPY src path
COPY . .
CMD ["node", "server.js"]

