components:
  parameters:
    maxResults:
      name: max
      in: query
      description: Returns <= maxResults results
      required: true
      schema:
        type: integer
        format: int32
      
    startResults:
      name: start
      in: query
      description: Returns results starting and including from the nth result
      required: true
      schema:
        type: integer
        format: int32
    
    endResults:
      name: end
      in: query
      description: Returns results up to but not including the nth result
      required: false
      schema:
        type: integer
        format: int32
    
    queryString:
      name: q
      in: query
      description: The search query that is provided to the search operation
      required: true
      schema:
        type: string
        format: string

    listingID:
      name: listingID
      in: query
      description: The id used to identify any listing
      required: true
      schema:
        type: string
        format: string

    category:
      name: category
      in: query
      description: Describes the category when selecting results
      required: false
      schema:
        type: string
        format: string
    
    reset-token:
      name: token
      in: query
      description: The token required in order to execute the password reset
      required: true
      schema:
        type: string
        format: id

    userID:
      name: userID
      in: query
      description: The User's id
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'

    reportID:
      name: reportID
      in: query
      description: The report's id
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'

    sanctionID:
      name: sanctionID
      in: query
      description: The sanction's id
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'

    conversationID:
      name: conversation's
      in: query
      description: The conversation's id
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'