components:
  parameters:
    maxResults:
      name: max
      in: query
      description: Returns <= max results
      required: true
      schema:
        type: integer
        format: int32

      
    startResults:
      name: start
      in: query
      description: Returns results starting and including from the nth result
      required: true
      schema:
        type: integer
        format: int32

    queryString:
      name: q
      in: query
      description: The search query that is provided to the search operation
      required: true
      schema:
        type: string
        format: string


    listingID:
      name: listingID
      in: query
      description: The ID used to identify any listing
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'


    ## To get available category descriptors use the category-descriptor-list endpoint
    categoryId:
      name: categoryID
      in: query
      description: Describes the categoryID when selecting results,
      required: false
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'


    resetToken:
      name: token
      in: query
      description: The token required in order to execute the password reset
      required: true
      schema:
        type: string
        format: id


    userID:
      name: userID
      in: query
      description: The User's ID
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'


    conversationID:
      name: conversationID
      in: query
      description: The conversation's ID
      required: true
      schema:
        $ref: 'schemas.yaml#/components/schemas/id'


    region:
      name: region
      in: query
      description: The region where a listing pickup is specified
      required: false
      schema:
        $ref: 'schemas.yaml#/components/schemas/region'